#!/usr/bin/env python

import sys

'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''


# Original Solution
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        sum_s = 0
        sum_t = 0
        for i in range(len(s)):
            sum_s += ord(s[i])
            sum_t += ord(t[i])
        sum_t += ord(t[len(s)])
        return chr(sum_t - sum_s)


# XOR solution(faster)
class SolutionXOR(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        num = 0
        for i in s:
            num ^= ord(i)
        for i in t:
            num ^= ord(i)
        return chr(num)


def validate_strs(s, t):
    if len(t) - len(s) != 1:
        return False
    for i in s:
        if i not in t:
            return False

    return True


if __name__ == "__main__":
    solution = Solution()
    solution_xor = SolutionXOR()
    s = raw_input("Please input string s: ")
    t = raw_input("Please input string t: ")

    if not validate_strs(s, t):
        sys.exit("Input strings don't match the requirements")

    print("The extra character is {}".format(solution.findTheDifference(s, t)))
    print("The result with xor solution is: {}".format(solution_xor.findTheDifference(s, t)))
